using System;
using System.IO;
using System.Linq;
using System.Text;
using Impostor.Api.Games;
using Boot.Codes.Handlers;
using Boot.Codes.Properties;
using System.Collections.Generic;
using System.Collections.Concurrent;
using Impostor.Api.Events.Managers;
using Microsoft.Extensions.Logging;

namespace Boot.Codes
{
    public class GameCodeManager : IGameCodeManager
    {
        private readonly ConcurrentQueue<GameCode> _codes;

        private readonly ConcurrentDictionary<GameCode, bool> _inUse;

        private readonly ILogger<IGameCodeManager> _logger;

        private readonly IGameCodeFactory _codeFactory;

        public string Path => "Boot.Codes.txt";

        public GameCodeManager(ILogger<GameCodeManager> logger, IGameCodeFactory codeFactory, IEventManager eventManager)
        {
            this._logger = logger;
            this._codeFactory = codeFactory;
            logger.LogInformation("Boot.Codes: Reading file.");

            var validCodes = Read().Select(code => new GameCode(code)).Where(code => !code.IsInvalid).ToList();
            validCodes.Shuffle();

            if (validCodes.Count == 0)
            {
                _logger.LogError("Boot.Codes: No codes loaded.");
                return;
            }

            this._codes = new ConcurrentQueue<GameCode>(validCodes);
            this._inUse = new ConcurrentDictionary<GameCode, bool>();

            _logger.LogInformation("Boot.Codes: Loaded {Count} codes.", this._codes.Count);
            eventManager.RegisterListener(new GameEventListener(this));
        }

        private IEnumerable<string> Read()
        {
            if (File.Exists(Path))
            {
                var lines = File.ReadAllLines(Path, Encoding.UTF8).Select(line => line.Trim().ToUpper()).ToArray();
                var invalid = lines.Where(line => line.Length != 6);
                var valid = lines.Where(line => line.Length == 6).ToArray();

                foreach (var line in invalid)
                {
                    _logger.LogWarning("Boot.Codes: The code \"{line}\" is invalid", line);
                }

                return valid;
            }

            _logger.LogWarning("Boot.Codes: Could not find list in \"{path}\". Using built-in list", Path);
            var text = Resources.defaultWords;
            File.WriteAllText(Path, text, Encoding.UTF8);
            return text.Split(new[] { Environment.NewLine }, StringSplitOptions.None);
        }

        public GameCode Get()
        {
            if (!this._codes.TryDequeue(out var code)) return _codeFactory.Create();
            _inUse.TryAdd(code, false);
            return code;
        }

        public void Release(GameCode code)
        {
            if (!_inUse.ContainsKey(code)) return;
            _inUse.Remove(code, out _);
            _codes.Enqueue(code);
            // else, it was generated by the factory.
        }
    }
}
